[project]
name = "diabetesped"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "joblib>=1.5.3",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "pyngrok>=7.5.0",
    "scikit-learn==1.6.1",
]
